#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to respect given requirements
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
